# Generated by Django 4.1.1 on 2023-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Path",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_name", models.CharField(max_length=50)),
            ],
        ),
    ]
