# Generated by Django 4.1.5 on 2023-01-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fisrt_name", models.CharField(max_length=50, verbose_name="adı")),
                ("last_name", models.CharField(max_length=50, verbose_name="soyadı")),
                ("number", models.IntegerField(verbose_name="numara")),
            ],
        ),
    ]
