# Generated by Django 4.1.1 on 2023-01-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fscohort", "0002_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="about",
            field=models.TextField(blank=True, null=True, verbose_name="Hakkında"),
        ),
        migrations.AddField(
            model_name="student",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="meida/", verbose_name="resim"
            ),
        ),
    ]
