# Generated by Django 4.1.5 on 2023-01-03 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("fscohort", "0003_student_about_student_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="country",
            field=models.CharField(
                choices=[
                    ("TR", "Turkey"),
                    ("US", "America"),
                    ("DE", "Germany"),
                    ("FR", "France"),
                ],
                default="TR",
                max_length=2,
                verbose_name="Ülke",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="register_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
