# Generated by Django 4.1.5 on 2023-01-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relations", "0002_freamwork"),
    ]

    operations = [
        migrations.CreateModel(
            name="Develepor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("freamwork", models.ManyToManyField(to="relations.freamwork")),
            ],
            options={
                "ordering": ["first_name"],
            },
        ),
    ]
